import Head from 'next/head';
import Image from 'next/image';
import Footer from './components/footer';
import Logo from './components/logo';
import Menu from './components/menu';
import ComeFindUs from './components/primary/come-find-us';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="rooster">
        <Logo className="rooster__logo" />
        <div className="rooster__primary">
          <h1>
            <span>The</span>
            <span>Roosters</span>
            <span>Rest</span>
          </h1>
          <ComeFindUs />
          <img src="/images/promo-box.jpg" />
          <h2>After Eating</h2>
          <img src="/images/promo-npa.jpg" />
          <Footer />
        </div>
        <div className="rooster__menu">
          <Menu />
        </div>
      </main>
    </>
  );
}
